Install Instructions for Beginners
Discord-FurDevs/FurDevs-Bot pull request #37
Opened 2020-12-13 18:57 UTC by EchoLynx

This was originally #34, but it was approved by @DeveloperDrago before @thetayloredman had a chance to comment on it, so @thetayloredman created #35 to revert it and #36 on their own branch to make the comments... but I'm not a contributor so I can't commit to #36, so here we are, on #37.

Should have all the suggested changes from #36, though!

2020-12-13 19:12 UTC, EchoLynx commented
@thetayloredman  @DeveloperDrago 
Ready for your review!

2020-12-13 19:41 UTC, thetayloredman commented
Lol...

2020-12-13 19:54 UTC, thetayloredman requested changes
For now, you can have this.

2020-12-13 19:54 UTC, thetayloredman commented on README.md
> +# About
```suggestion
## About
```

The top-level header already exists as the `<h1>` above this.

2020-12-13 19:54 UTC, thetayloredman commented on README.md
> +4. Start the bot by doing `node .` or `node index.js`.
```suggestion
4. Start the bot by doing `node .`.
```

Maybe it's a little confusing for new people with 2 possible commands? Would using a start script work? `npm start` or `./start.sh`

2020-12-13 19:54 UTC, thetayloredman commented on README.md
> +You should see that a new folder was created falled "FurDevs-Bot".
```suggestion
You should see that a new folder was created falled "FurDevs-Bot". Now we enter that folder like this:
`cd FurDevs-Bot`
```

2020-12-13 19:54 UTC, thetayloredman commented on README.md
> +`npm i`
```suggestion
`npm install`
```

`npm i` is a little confusing for beginners

2020-12-13 19:54 UTC, thetayloredman commented on README.md
> +The TOKEN is the identifier that we get from Discord to identify our instance of the bot. With it, Discord can differentiate between different instances of the same bot. We have to get one generated
```suggestion
The TOKEN is the identifier that we get from Discord to identify our instance of the bot. With it, Discord can differentiate between different instances of the same bot. We have to get one generated to use for our instance. We also have to be careful to protect it, as sharing it would allow others to impersonate our bot. (If you've ever used another API before, it's basically your "API Key")
```

2020-12-13 19:54 UTC, thetayloredman commented on README.md
> +6. Underneath the Bot's username and to the right of the Bot's icon is a link that says "Click to Reveal Token". Click it and copy it into your `.env` file!
```suggestion
6. Underneath the Bot's username and to the right of the Bot's icon is a link that says "Click to Reveal Token". Click it and copy it into your `.env` file after `TOKEN=`!
```

2020-12-13 19:54 UTC, thetayloredman commented on README.md
> +1. Go to the "OAuth 2" section in the menu on the left hand side of the page.
```suggestion
1. Go to the "OAuth2" section in the menu on the left hand side of the page.
```

2020-12-13 21:34 UTC, EchoLynx commented on README.md
> +4. Start the bot by doing `node .` or `node index.js`.
Everything in the Quick Start section is a minimally changed version of what's currently in README.md. I didn't want to change any of that in the event that a contributor was already using it as a reference and expected it to look a certain way. The only changes made to that section were those you've suggested thus far.

That said, reducing the ambiguity here makes sense. It's the quick start section - no need to have alternatives.

Along those lines, I don't think that adding `npm start` here would really help much in terms of either newbies or experienced users getting this running.  `./start.sh` would just abstract the one line `node .`, so I don't think we gain any ease-of-use from abstracting it away. It's not like getting the bot running in a discord server is a process that we're trying to automate into a one-step shell script... although... nope -  might be worth exploring, but certainly out of scope here.

2020-12-13 21:39 UTC, EchoLynx commented on README.md
> +# About
Yea, I wasn't sure what to do here. The linter I ran this through said I should correct it, so I did. I don't particularly care either way, so let's put it back.

2020-12-13 21:40 UTC, EchoLynx commented
@thetayloredman @DeveloperDrago 
Ready for your review!

2020-12-13 23:39 UTC, thetayloredman commented
fun fact: you could have batched those all into one commit with the "Add to batch" button

2020-12-13 23:43 UTC, thetayloredman requested changes
Looking good so far!!

2020-12-13 23:43 UTC, thetayloredman commented on README.md
> +2. Run `npm i`.
```suggestion
2. Run `npm install`.
```

This too :)

2020-12-13 23:43 UTC, thetayloredman commented on README.md
> +Once your `.env` file is configured, save and close it, the return to your Git Bash window and run the following to start the bot:
```suggestion
Once your `.env` file is configured, save and close it, the return to your Git Bash window and run the following to start the bot:
`node .`

Also, it might be scary at first if you see a bunch of text flood down your terminal! Don't worry, this is completely normal. It's the bot's debugging output telling you what is happening.
```

2020-12-13 23:44 UTC, EchoLynx commented
> fun fact: you could have batched those all into one commit with the "Add to batch" button

Good to know, will try this time around.

2020-12-13 23:52 UTC, EchoLynx commented on README.md
> +Once your `.env` file is configured, save and close it, the return to your Git Bash window and run the following to start the bot:
Good thought, adding this part!

2020-12-13 23:54 UTC, EchoLynx commented
Batching changes worked like a charm!

@thetayloredman @DeveloperDrago 
Ready for review!

2020-12-13 23:59 UTC, thetayloredman approved these changes
Looking good! @DeveloperDrago, your opinion?

2020-12-14 00:03 UTC, DeveloperDrago commented
Looks good to me 😀

2020-12-14 00:04 UTC, merged